spring:
  data:
    redis:
      host: localhost
      password: session
      port: 6379
      url: redis://localhost:6379
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
  session:
    redis:
      cleanup-cron: 0 * * * * *
      flush-mode: on_save
      namespace: spring:session
    timeout: 1m
  sql:
    init:
      continue-on-error: true
      mode: always
      schema-locations: classpath:schema.sql