spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      enabled: false
    gcp:
      sql:
        database-name: postgres
        instance-connection-name: culinary-portal:europe-central2:culinary-postgres-db
      credentials:
        encoded-key: ${GCP_SA_JSON}
  data:
    redis:
      host: localhost
      password: session
      port: 6379
      url: redis://localhost:6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          default_schema: public
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public