spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      enabled: false
    gcp:
      sql:
        database-name: postgres
        instance-connection-name: culinary-portal:europe-central2:culinary-postgres-db
      credentials:
        location: file:service-account-file.json
  data:
    redis:
      host: localhost
      password: session
      port: 6379
      url: redis://localhost:6379

