server:
  servlet:
    session:
      cookie:
        domain: localhost
        http-only: true
        max-age: 600
        name: JSESSIONID
        path: /
        same-site: strict
        secure: false
      timeout: 1m
      tracking-modes: cookie

spring:
  cloud:
    gcp:
      sql:
        enabled: false

admin.email: admin@admin.com
default.user.photo.url: "N/A"

custom.max.session: 1

allowed.origins:
  local: "http://localhost:4200"
  cloud-front: "https://culinary-frontend-service-dot-culinary-portal.lm.r.appspot.com/"
  cloud-api: "https://culinary-user-service-dot-culinary-portal.lm.r.appspot.com/"
### JDBC logs
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        jdbc: TRACE
        security: ERROR




      
