spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      enabled: false
    gcp:
      sql:
        enabled: true
        database-name: postgres
        instance-connection-name: culinary-portal:europe-central2:culinary-postgres-db
      credentials:
        encoded-key: ${GCP_SA_JSON}
  data:
    redis:
      host: 10.241.218.123
      port: 6379
      ssl:
        enabled: false

  redis:
    ssl=false: