runtime: custom
env: flex
service: culinary-user-service

instance_class: F1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud"
  DB_USERNAME: DB_USERNAME_PLACEHOLDER
  DB_PASSWORD: DB_PASSWORD_PLACEHOLDER
  GCP_SA_JSON: GCP_SA_JSON_PLACEHOLDER

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
