runtime: custom
env: flex

instance_class: F1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud"


resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
